apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: default
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: tasklinedb
  DB_USER: taskline
  DB_PASSWORD: taskline123
